export { default as HomePage } from './HomePage'
export { default as BlogPage } from './BlogPage'
export { default as ArticlePage } from './ArticlePage'
export { default as ConciergePage } from './ConciergePage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
